S01US29
WildCodeSchool-2023-09/JS-RemoteFR-CrewStillant-P3-EatingNamNam pull request #47
Opened 2023-12-19 17:07 UTC by Mewlyscin

create navbar
page : UserCompte and MyRecipe
update main: router /UserCompte and MyRecipe

2023-12-20 00:07 UTC, PierreA44 commented on frontend/src/App.jsx
> +// router react
Useless

2023-12-20 00:07 UTC, PierreA44 commented on frontend/src/App.jsx
> +// my imports
Useless

2023-12-20 00:07 UTC, PierreA44 commented on frontend/src/components/Navbar.jsx
> +// import logo
Useless

2023-12-20 00:07 UTC, PierreA44 commented on frontend/src/components/Navbar.jsx
> +// my function nav
Useless

2023-12-20 00:07 UTC, PierreA44 commented on frontend/src/components/Navbar.jsx
> +      <NavLink className="m-2" to="/home">
this path does'nt exist

2023-12-20 00:07 UTC, PierreA44 commented on frontend/src/main.jsx
> +// import react
Useless

2023-12-20 00:07 UTC, PierreA44 commented on frontend/src/main.jsx
> +import MyRecipe from "./pages/MyRecipe";
MyRecipe isn't a good syntax... use RecipePage

2023-12-20 00:07 UTC, PierreA44 commented on frontend/src/main.jsx
> +import UserCompte from "./pages/UserCompte";
French and English in same namefile... bad... use UserAccountPage or UserPage

2023-12-20 00:07 UTC, PierreA44 commented on frontend/src/main.jsx
> +// imports page
Useless

2023-12-20 00:07 UTC, PierreA44 commented on frontend/src/main.jsx
> +// router
Useless

2023-12-20 00:08 UTC, PierreA44 requested changes
Fix many problems

2023-12-20 08:08 UTC, QuentinVerwaerde requested changes
Nice but like said before me, some changes are necessary : 
names should be in english only
no commented text in generally allowed 
you can't use a path that does not exist in a Navlink : you'll need to create it or modify it

2023-12-20 11:01 UTC, PierreA44 approved these changes
nice work. thanks for changes

2023-12-20 11:13 UTC, bayram-69 approved these changes

2023-12-20 11:25 UTC, akornne approved these changes

2023-12-20 14:12 UTC, ioayoub requested changes

2023-12-20 14:12 UTC, ioayoub commented on .gitignore
> +.env
updating this file is not allowed, you already have .gitgnore file on both front and backend folders

2023-12-20 14:12 UTC, ioayoub commented on frontend/src/pages/RecipePage.jsx
> +function MyRecipe() {
Empty pages are not allowed.

2023-12-20 14:12 UTC, ioayoub commented on frontend/src/pages/UserAccountPage.jsx
> +function UserAccountPage() {
Empty pages are not allowed.

2023-12-21 13:56 UTC, ioayoub approved these changes

2023-12-21 14:00 UTC, merged