feat: button recipe creation, loader is ok
WildCodeSchool-2023-09/JS-RemoteFR-CrewStillant-P3-EatingNamNam pull request #52
Opened 2023-12-21 13:39 UTC by bayram-69

2023-12-21 13:59 UTC, ioayoub requested changes

2023-12-21 13:59 UTC, ioayoub commented on frontend/src/main.jsx
> +          const response = await fetch("http://localhost:3310/api/recipe");
prefer using : await fetch("myurl.com").then(res => res.json)

2023-12-21 13:59 UTC, ioayoub commented on frontend/src/pages/NewRecipePage.jsx
> +function NewRecipePage() {
❌ - Empty files are not allowed

2023-12-21 14:54 UTC, QuentinVerwaerde approved these changes

2023-12-21 15:15 UTC, PierreA44 approved these changes

2023-12-21 15:19 UTC, Mewlyscin approved these changes

2023-12-21 20:13 UTC, ioayoub requested changes

2023-12-21 20:13 UTC, ioayoub commented on backend/seed.js
> +    await database.query("DELETE FROM recipe");
Prefer a TRUNCATE here

2023-12-21 20:13 UTC, ioayoub commented on frontend/src/main.jsx
> +          const recipes = await fetch("http://localhost:3310/api/recipe").then(
Use env variable instead of complete url

2023-12-22 11:19 UTC, akornne approved these changes

2023-12-22 20:45 UTC, ioayoub requested changes

2023-12-22 20:45 UTC, ioayoub commented on frontend/src/components/Recipes.jsx
> +function Recipes() {
Empty files are not allowed

2023-12-24 10:25 UTC, ioayoub approved these changes

2023-12-26 20:44 UTC, merged