feat: add recipe details
WildCodeSchool-2023-09/JS-RemoteFR-CrewStillant-P3-EatingNamNam pull request #60
Opened 2024-01-04 15:38 UTC by bayram-69

2024-01-04 17:43 UTC, PierreA44 commented on frontend/src/pages/HomePage.jsx
> +                    <button
is it usefull to use a button in a navlink if we don't "use" the button ?

2024-01-04 17:44 UTC, PierreA44 approved these changes

2024-01-05 08:57 UTC, QuentinVerwaerde approved these changes

2024-01-05 09:21 UTC, Mewlyscin approved these changes

2024-01-05 09:22 UTC, ioayoub requested changes

2024-01-05 09:22 UTC, ioayoub commented on frontend/src/pages/RecipesPage.jsx
> +import { useLoaderData } from "react-router-dom";
remove this if not used. Empty pages are not allowed

2024-01-05 09:28 UTC, ioayoub approved these changes

2024-01-05 09:29 UTC, merged