Feat : add Comments field form in recipe page.
WildCodeSchool-2023-09/JS-RemoteFR-CrewStillant-P3-EatingNamNam pull request #66
Opened 2024-01-11 08:13 UTC by PierreA44

2024-01-11 12:53 UTC, Mewlyscin approved these changes

2024-01-11 13:05 UTC, bayram-69 approved these changes

2024-01-11 13:06 UTC, akornne approved these changes

2024-01-11 17:20 UTC, ioayoub approved these changes

2024-01-12 08:42 UTC, QuentinVerwaerde requested changes

2024-01-12 08:42 UTC, QuentinVerwaerde commented on frontend/src/pages/RecipesPage.jsx
> +  useEffect(() => {
Good but can you comment those lines with their use please ?

2024-01-12 10:13 UTC, QuentinVerwaerde approved these changes

2024-01-12 10:13 UTC, merged