FEAT : Add admistration user page
WildCodeSchool-2023-09/JS-RemoteFR-CrewStillant-P3-EatingNamNam pull request #81
Opened 2024-01-24 15:16 UTC by PierreA44

2024-01-24 15:28 UTC, akornne approved these changes

2024-01-24 18:04 UTC, Mewlyscin approved these changes

2024-01-24 19:54 UTC, ioayoub requested changes

2024-01-24 19:54 UTC, ioayoub commented on backend/src/models/UserManager.js
> +  // , COUNT(rc.recipe_id) AS total_recipe JOIN recipe_comment AS rc ON rc.user_id=u.id
👀

2024-01-24 19:54 UTC, ioayoub commented on frontend/src/pages/HomePage.jsx
> +// import timer from "../assets/timer/minuteur.png";
👀

2024-01-24 19:54 UTC, ioayoub commented on frontend/src/pages/UserPage.jsx
> +      path: `/user/info/${auth.id}`,
This is a security issue, you already have all needed informations to retrieve the current user in your database.

2024-01-25 10:38 UTC, QuentinVerwaerde approved these changes

2024-01-25 16:10 UTC, PierreA44 commented
NE PAS MERGER!!!!!!

2024-01-25 16:37 UTC, merged