S04US15
WildCodeSchool-2023-09/JS-RemoteFR-CrewStillant-P3-EatingNamNam pull request #84
Opened 2024-01-25 17:22 UTC by Mewlyscin

create button Favorite and logic

2024-01-25 17:28 UTC, PierreA44 commented on frontend/src/components/FavRecipe.jsx
> +
component not necessary, delete this file please

2024-01-25 17:29 UTC, PierreA44 commented on frontend/src/main.jsx
> +            path: "/user/favorite/:id",
delete this children please, the component to display favorite recipe is already created

2024-01-25 17:29 UTC, PierreA44 requested changes
some little changes

2024-01-25 17:59 UTC, PierreA44 approved these changes

2024-01-25 19:33 UTC, QuentinVerwaerde approved these changes

2024-01-25 20:06 UTC, bayram-69 approved these changes

2024-01-26 08:05 UTC, akornne approved these changes

2024-01-26 08:05 UTC, ioayoub approved these changes

2024-01-26 08:12 UTC, merged